### ISSUE TITLE
Make call /timeSlots/{date}

### ISSUE THREAD

**Issue by NeuserThomas** [NeuserThomas/project-system-design#13]
make call that returns all timeslot for the present planning

necessary fields:
- Id
- MovieTitle
- AvailableSpots
- hallNumber (not hallId)
- startTime

**Comment by RobinGoussey** [comment]
@NeuserThomas Ge zult ze zo allemaal krijgen /TimeSlots/getByDate/{date}, via /TimeSlots/getByCinemaId/{cinemaid}/{date} krijg je er  , of via /timeSlots/getByCinemaName/{cinemaName}/{date} kan je ze ook per naam krijgen.

**Comment by RobinGoussey** [comment]
Werkt dit nu zoals behoren @NeuserThomas ? # #

**Comment by NeuserThomas** [comment]
Ja maar ik kan het nog niet deftig verwerken, kzal er na beveiliging (7jan)
aan verder doen
