### ISSUE TITLE
Deploying kafka on kubernetes

### ISSUE THREAD

**Issue by RobinGoussey** [NeuserThomas/project-system-design#16]

**Comment by RobinGoussey** [comment]
Ik heb een deel gepushed (zie laatste kubernetes commit). Heb kan dat de naam wel nog moet aangepast worden.

**Comment by NeuserThomas** [comment]
Issue fixed: 
In spring properties file
spring.blabla.blabla.bootstrap-servers:bootstrap.kafka:9092
